### ISSUE TITLE
Fail to install l5kit==1.5.0

### ISSUE THREAD

**Issue by Iven-Wu** [NVlabs/CTG#6]
When I ran the setup.py, it turned out to install l5kit==1.2.0 even though it was told to install 1.5.0.  How can it be fixed?

**Comment by Iven-Wu** [comment]
It seems that the dependency         
"l5kit==1.5.0",
"numpy==1.23.4" have some conflicts.

**Comment by Iven-Wu** [comment]
Seems be solved by using python 3.8

**Comment by hairuoliu1** [comment]
Are there any other changes?

**Comment by ApisXia** [comment]
The installation can be conducted manually by modifying certain package versions in "l5kit/setup.py" of the l5kit git repository. I made the following changes, which are compatible with Python 3.10:
- "protobuf==3.20.1"
- "shapely==2.0.6"
- "bokeh==3.0.3"
Please comment out "l5kit==1.5.0" in CTG first.

**Comment by liyi0813** [comment]
> Seems be solved by using python 3.8
Hello, did you encounter any issues when installing in py3.8? Do you have a solution for this problem that occurred in py3.9?
您好，你在py3.8中安装没有问题吗？py3.9中出现了这个问题你有解决的方案吗？
<img width="1097" height="200" alt="Image" src="https://github.com/user-attachments/assets/1abe7827-b7e5-4b00-82bf-4add8c7acf16" />
